### ISSUE TITLE
Getting window size instead of device's screen

### ISSUE THREAD

**Issue by davidetruffo** [mishbahr/django-responsive2#1]
Hi!
would that be even possible? :)
i mean.. if i use a very small browser window on a very big screen, i still get the big images served, but i shouldn't.

**Comment by mishbahr** [comment]
Its definitely possible, we could listen for window resize event and reload the content. But I'm not too keen on reloading content on window resize! To keep the development simple, few assumption had to be made. For my usecase, 40% or more of the traffic is from mobiles or tablets, where the visitor don't actually have the options to resize the browser (so it was assumed that visitors are browsing in full screen mode).

**Comment by davidetruffo** [comment]
I get your point. I think on mobile/tablets, the window resize is actually possible (rotating the device, for example). Anyway, what i meant is that on a big screen, or not necessarily so big, the user could decide not to use the browser in full screen. Detecting the screen-size would always return bigger images than needed :) 

(as practical example, i'm working on a 27" now, but even on a 15", i never let the browser window to take all the screen, but i always get xxlarge images because of the screen) 

It could be nice to have it as a setting: LISTEN_TO_WINDOW_SIZE = True/False, even without resize event. Just getting the window size on load instead of the device size

**Comment by mishbahr** [comment]
I guess if you don't care about window resize .. this would be very easy to implement.  You could just override the template `'responsive/snippet.html'` to use window size.

But this is something I don't plan to implement myself for this package.

**Comment by davidetruffo** [comment]
Thanks for the hint! I'll give it a try!

**Comment by mishbahr** [comment]
I'll close this for now! If you have any other questions .. feel free to reopen this ticket!

Thanks.

— Mishbah

**Comment by mishbahr** [comment]
Hey @davidetruffo, I've updated https://github.com/mishbahr/djangocms-responsive-wrapper to use window dimensions with live reload on window resize, it uses `django-responsive2` for evaluating the rules. 

Thanks for the inspiration :-)
