### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by romeo09** [mishbahr/django-responsive2#10]
How do I Resolve this problem?  ImportError: Module "responsive.middleware" does not define a "ResponsiveMiddleware" attribute/class

**Comment by mishbahr** [comment]
Can I have a look at your `MIDDLEWARE_CLASSES` setting for your project?

**Comment by mishbahr** [comment]
No response from OP. Feel free to reopen this .. if you still having an issue. Thanks.
