### ISSUE TITLE
b'<head(.*?)>' - not even funny

### ISSUE THREAD

**Issue by a-olszewski** [mishbahr/django-responsive2#4]
we are in HTML5 world now :dizzy_face:

**Comment by a-olszewski** [comment]
now seriously, you don't want to match each html5 header element :smile:

**Comment by mishbahr** [comment]
Ooops! Totally didn't think of that. Apologies.

Thank You for raising it as an issue.

Please use version 0.1.1 for now.. I'll push a fix as soon as I can.

Regards

Mishbah

**Comment by mishbahr** [comment]
Thanks @CptLemming for your help!

**Comment by a-olszewski** [comment]
no problem :) you did a great job with that app! I am glad I could help
