### ISSUE TITLE
Would be convenient to match default media queries to Bootstrap rather than Zurb

### ISSUE THREAD

**Issue by YPCrumble** [mishbahr/django-responsive2#9]
Great repo, thanks for building! 

I was looking to implement this and saw the reference to `if device.is_xsmall` in the README that corresponds to Bootstrap's terminology. It would be convenient to simply adjust the default `MEDIA_QUERIES` settings to match bootstrap rather than Zurb foundation as currently implemented.

Happy to make a PR if you agree and would find it helpful!

**Comment by mishbahr** [comment]
Im not so keen on changing default config.  This would break peoples project. Its is based on Foundation 5 media queries: http://foundation.zurb.com/sites/docs/v/5.5.3/media-queries.html

It is settings driven, you can easily use bootstrap by defining your own `RESPONSIVE_MEDIA_QUERIES` setting.

**Comment by mishbahr** [comment]
I'll happy to add it as an example in the README file .. so its easier for other people to copy/paste.

**Comment by YPCrumble** [comment]
@mishbahr great idea, thanks! I'll make that PR soon as I've completed for my project.
